# Generated by Django 3.2 on 2021-05-14 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workday', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caculator',
            new_name='Calculator',
        ),
    ]
