# Generated by Django 3.2 on 2021-05-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0003_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workday.calculator')),
            ],
        ),
    ]
