# Generated by Django 3.2 on 2021-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0005_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(help_text='날짜 형식: <em>YYYY-MM-DD (ex)2021-01-01</em>'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(help_text='날짜 형식: <em>YYYY-MM-DD (ex)2021-01-01</em>'),
        ),
    ]
