# Generated by Django 3.2 on 2021-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0007_auto_20210521_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
