# Generated by Django 3.2.9 on 2021-12-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0009_calculator_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='end_date',
            field=models.DateField(help_text='날짜형식: 2021-01-01'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='start_date',
            field=models.DateField(help_text='날짜형식: 2021-01-01'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(help_text='날짜형식: 2021-01-01'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(help_text='날짜형식: 2021-01-01'),
        ),
    ]
