# Generated by Django 3.2 on 2021-07-18 02:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0008_alter_calculator_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barracks', '0002_barrackscomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarracksComment',
            new_name='GuestBook',
        ),
    ]
