# Generated by Django 3.2 on 2021-07-19 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0008_alter_calculator_name'),
        ('barracks', '0004_auto_20210718_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='inviter_calculator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='my_invitations', to='workday.calculator'),
            preserve_default=False,
        ),
    ]
