# Generated by Django 3.2 on 2021-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barracks', '0005_invitation_inviter_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='barracks',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
