# Generated by Django 3.2.9 on 2021-12-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
