# Generated by Django 3.2.9 on 2022-01-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttag',
            name='slug',
        ),
    ]
