# Generated by Django 3.2.9 on 2021-12-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_restaurant_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastrestaurant',
            name='region',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
