# Generated by Django 3.2.9 on 2021-12-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_remove_restaurant_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
