# Generated by Django 3.2.9 on 2021-12-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_alter_restaurant_verifieded'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
