# Generated by Django 3.2.9 on 2021-12-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_restaurant_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, help_text='생략시 <가게 상호>를 구체적으로 입력해주시면 감사하겠습니다. (ex: 최고다삽겹살 고다역점)', max_length=200, null=True),
        ),
    ]
