# Generated by Django 3.2.9 on 2021-12-31 22:03

import corona.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_fastrestaurant_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastrestaurant',
            name='base_pk',
            field=models.IntegerField(blank=True, null=True, verbose_name=corona.models.Restaurant),
        ),
    ]
