# Generated by Django 3.2.9 on 2021-12-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_restaurant_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
