# Generated by Django 3.2.9 on 2021-12-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_alter_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, help_text='주소 생략시 <가게 상호>을 구체적으로 입력해주세요. (예시: 최고다삽겹살 고다역점)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
