# Generated by Django 3.2.9 on 2022-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_fastrestaurant_base_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, null=True, unique=True),
        ),
    ]
