# Generated by Django 3.2.9 on 2022-01-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_restauranttag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttag',
            old_name='slug',
            new_name='slug2',
        ),
    ]
