# Generated by Django 3.2.9 on 2021-12-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_auto_20211225_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
