# Generated by Django 3.2.9 on 2021-12-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0007_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='<미접종 친절>의 경우 아래 태그를 통해 PCR 음성 필요 여부를 작성해주시면 감사하겠습니다.', to='corona.RestaurantTag'),
        ),
    ]
