# Generated by Django 3.2.9 on 2021-12-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0008_alter_restaurant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(help_text='<미접종 친절>의 경우 아래 태그를 통해 PCR 음성 필요 여부를 작성해주시면 감사하겠습니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.restaurantcategory'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='corona.RestaurantTag'),
        ),
    ]
