# Generated by Django 3.2.9 on 2021-12-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0011_alter_restaurant_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(help_text='<a href="https://map.naver.com/v5/" class="text-decoration-none small">\n        <img src="https://res.cloudinary.com/hyzq6bxmk/image/upload/v1640650504/static/corona/naver_map_yc6xld.png" \n        style="width: 20px; height: 20px">\n        네이버 지도에서 알아보기\n    </a>', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='unvaccinated_pass',
            field=models.ForeignKey(help_text='이용가능 여부 확인이 필요하시면 <궁금>으로 설정해주세요', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corona.unvaccinatedpass'),
        ),
    ]
