# Generated by Django 3.2.9 on 2021-12-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0014_fastrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastrestaurant',
            name='num_hits',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fastrestaurant',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
