# Generated by Django 3.2.9 on 2021-12-29 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0015_auto_20211229_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastrestaurant',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corona.restaurant'),
        ),
    ]
