# Generated by Django 3.2.9 on 2021-12-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0016_fastrestaurant_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcomment',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='corona/restaurant/comments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(help_text='<a href="https://map.naver.com/v5/" class="text-decoration-none small" target="_blank">\n        <img src="https://res.cloudinary.com/hyzq6bxmk/image/upload/v1640650504/static/corona/naver_map_yc6xld.png" \n        style="width: 20px; height: 20px">\n        네이버 지도에서 알아보기\n    </a>', max_length=200, null=True),
        ),
    ]
