# Generated by Django 3.2.9 on 2021-12-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0017_auto_20211229_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantcomment',
            old_name='head_image',
            new_name='image',
        ),
    ]
