# Generated by Django 3.2.9 on 2021-12-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0020_alter_restaurantcomment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantcomment',
            name='image',
        ),
    ]
