# Generated by Django 3.2.9 on 2021-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0021_remove_restaurantcomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcomment',
            name='image',
            field=models.ImageField(blank=True, upload_to='corona/restaurant/comments/%Y/%m/%d/'),
        ),
    ]
