# Generated by Django 3.2.9 on 2021-12-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0023_alter_restaurantcomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcomment',
            name='image',
            field=models.ImageField(blank=True, default='/corona/static/corona/kakao_map.png/', upload_to='corona/restaurant/comments/%Y/%m/%d/'),
        ),
    ]
