# Generated by Django 3.2.9 on 2021-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0024_alter_restaurantcomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='corona/restaurant/comments/%Y/%m/%d/'),
        ),
    ]
