# Generated by Django 3.2 on 2021-05-09 18:12

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210508_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
