# Generated by Django 3.2 on 2021-09-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingchart',
            name='num_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
