# Generated by Django 3.2 on 2021-07-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corona',
            old_name='decideCnt',
            new_name='decide_count',
        ),
    ]
