# Generated by Django 3.2 on 2021-07-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_decidecnt_corona_decide_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corona',
            old_name='decide_count',
            new_name='decided_count',
        ),
    ]
