# Generated by Django 3.2 on 2021-08-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_decide_count_corona_decided_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateField()),
                ('user_count', models.IntegerField()),
                ('calculator_count', models.IntegerField()),
                ('leave_count', models.IntegerField()),
                ('barracks_count', models.IntegerField()),
                ('barracks_guest_book_count', models.IntegerField()),
                ('troop_count', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('post_count', models.IntegerField()),
                ('post_comment_count', models.IntegerField()),
                ('user_increment', models.IntegerField()),
                ('calculator_increment', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
