# Generated by Django 3.2 on 2021-08-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='barracks_guest_book_count',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='post_comment_count',
            new_name='guest_book_count',
        ),
    ]
