# Generated by Django 3.2 on 2021-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troop_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='discipline',
            field=models.CharField(choices=[('very_high', '빡세다'), ('high', '세다'), ('nomal', '보통'), ('low', '약하다'), ('very_low', '빠졌다')], default='nomal', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='training',
            field=models.CharField(choices=[('very_high', '매우 강하다'), ('high', '강하다'), ('nomal', '보통'), ('low', '약하다'), ('very_low', '매우 약하다')], default='nomal', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
