# Generated by Django 3.2 on 2021-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troop_review', '0005_review_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='training',
            field=models.CharField(choices=[('very_high', '매우 강함'), ('high', '강함'), ('nomal', '보통'), ('low', '약함'), ('very_low', '매우 약함')], default='nomal', max_length=9),
        ),
    ]
