# Generated by Django 3.2 on 2021-08-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troop_review', '0006_alter_review_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='discipline',
            field=models.CharField(choices=[('very_high', '매우 빡셈'), ('high', '빡셈'), ('nomal', '보통'), ('low', '빠짐'), ('very_low', '매우 빠짐')], default='nomal', max_length=9),
        ),
    ]
