# Generated by Django 3.2 on 2021-08-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troop_review', '0007_alter_review_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='training',
            field=models.CharField(choices=[('very_high', '매우 많음'), ('high', '많음'), ('nomal', '보통'), ('low', '적음'), ('very_low', '매우 적음')], default='nomal', max_length=9),
        ),
    ]
