# Generated by Django 3.2 on 2021-08-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
