# Generated by Django 3.2 on 2021-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_forum', '0002_videocomment_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='is_open',
        ),
        migrations.AddField(
            model_name='video',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
