# Generated by Django 3.2.9 on 2021-12-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_forum', '0003_auto_20210830_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotag',
            name='slug',
        ),
    ]
