# Generated by Django 3.2.9 on 2021-12-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_forum', '0006_auto_20211231_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
