# Generated by Django 3.2 on 2021-11-19 12:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_auto_20211119_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
