# Generated by Django 3.2 on 2021-11-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='image',
        ),
    ]
