# Generated by Django 3.2 on 2021-11-19 13:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0007_remove_face_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='temp',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
