# Generated by Django 3.2 on 2021-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0009_remove_face_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', '남자'), ('f', '여자')], default='m', max_length=1),
        ),
    ]
