# Generated by Django 3.2 on 2021-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0010_alter_face_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='gender',
            field=models.CharField(choices=[('m', '남자'), ('f', '여자(업데이트 예정)')], default='m', max_length=1),
        ),
    ]
